-- Baseline schema for Bike Trip Planner (pre-launch migration reset).
-- Generated by: pg_dump --schema-only --no-owner --no-privileges of a database
-- with all pre-reset migrations applied (verified schema-identical). Executed
-- verbatim by Version20260807130000 (the sole baseline migration). Do NOT hand-edit;
-- regenerate from a fresh migrate + pg_dump if the schema ever needs a new baseline.

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4


--
-- Name: osm; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA osm;


--
-- Name: provisioner; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA provisioner;


--
-- Name: tourism; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tourism;


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';




--
-- Name: accommodations; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.accommodations (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    category text NOT NULL,
    stars integer,
    capacity integer,
    fee text,
    website text,
    wikidata text,
    opening_hours text,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    description text,
    image_url text,
    wikipedia_url text,
    zone text,
    last_seen_at timestamp with time zone,
    CONSTRAINT accommodations_named_unless_shelter CHECK (((category = 'shelter'::text) OR (NULLIF(btrim(name), ''::text) IS NOT NULL)))
);


--
-- Name: admin_boundaries; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.admin_boundaries (
    osm_id bigint NOT NULL,
    name text,
    admin_level integer,
    tags jsonb,
    geom public.geometry(MultiPolygon,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: bike_shops; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.bike_shops (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    category text NOT NULL,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: charging_stations; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.charging_stations (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    category text NOT NULL,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: coverage; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.coverage (
    geom public.geometry(MultiPolygon,4326)
);


--
-- Name: cultural_pois; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.cultural_pois (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    category text NOT NULL,
    wikidata text,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    description text,
    opening_hours text,
    website text,
    image_url text,
    wikipedia_url text,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: cycle_routes; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.cycle_routes (
    osm_id bigint NOT NULL,
    name text,
    network text,
    ref text,
    tags jsonb,
    geom public.geometry(MultiLineString,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: ferries; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.ferries (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    tags jsonb,
    geom public.geometry(Geometry,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: fords; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.fords (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: health_services; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.health_services (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    category text NOT NULL,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: metadata; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.metadata (
    refreshed_at timestamp with time zone,
    feature_counts jsonb,
    completeness jsonb,
    rejections jsonb
);


--
-- Name: pois; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.pois (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    category text NOT NULL,
    opening_hours text,
    website text,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: railway_stations; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.railway_stations (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    category text NOT NULL,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: routing_perimeter; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.routing_perimeter (
    slug text NOT NULL,
    observed_at timestamp with time zone NOT NULL
);


--
-- Name: water_points; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.water_points (
    osm_type character(1) NOT NULL,
    osm_id bigint NOT NULL,
    name text,
    category text NOT NULL,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: ways; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.ways (
    osm_id bigint NOT NULL,
    tags jsonb,
    geom public.geometry(LineString,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: zones; Type: TABLE; Schema: osm; Owner: -
--

CREATE TABLE osm.zones (
    slug text NOT NULL,
    name text NOT NULL,
    country text NOT NULL,
    opened_at timestamp with time zone NOT NULL,
    refreshed_at timestamp with time zone NOT NULL,
    pipeline_version integer NOT NULL,
    feature_counts jsonb DEFAULT '{}'::jsonb NOT NULL,
    new_entries jsonb DEFAULT '{}'::jsonb NOT NULL,
    geom public.geometry(MultiPolygon,4326)
);


--
-- Name: place_enrichment; Type: TABLE; Schema: provisioner; Owner: -
--

CREATE TABLE provisioner.place_enrichment (
    source text NOT NULL,
    source_id text NOT NULL,
    payload jsonb NOT NULL,
    status text NOT NULL,
    resolver_version integer NOT NULL,
    fetched_at timestamp with time zone NOT NULL
);


--
-- Name: wikidata_cache; Type: TABLE; Schema: provisioner; Owner: -
--

CREATE TABLE provisioner.wikidata_cache (
    qid text NOT NULL,
    payload jsonb NOT NULL,
    fetched_at timestamp with time zone NOT NULL
);


--
-- Name: access_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_request (
    id uuid NOT NULL,
    email character varying(180) NOT NULL,
    ip character varying(45) NOT NULL,
    status character varying(32) NOT NULL,
    verified_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created_at timestamp(0) without time zone NOT NULL
);


--
-- Name: COLUMN access_request.id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.access_request.id IS '(DC2Type:uuid)';


--
-- Name: COLUMN access_request.verified_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.access_request.verified_at IS '(DC2Type:datetime_immutable)';


--
-- Name: COLUMN access_request.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.access_request.created_at IS '(DC2Type:datetime_immutable)';


--
-- Name: email_change_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_change_token (
    id uuid NOT NULL,
    token character varying(128) NOT NULL,
    new_email character varying(180) NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    consumed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created_at timestamp(0) without time zone NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: COLUMN email_change_token.expires_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.email_change_token.expires_at IS '(DC2Type:datetime_immutable)';


--
-- Name: COLUMN email_change_token.consumed_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.email_change_token.consumed_at IS '(DC2Type:datetime_immutable)';


--
-- Name: COLUMN email_change_token.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.email_change_token.created_at IS '(DC2Type:datetime_immutable)';


--
-- Name: magic_link; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.magic_link (
    id uuid NOT NULL,
    token character varying(128) NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    consumed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created_at timestamp(0) without time zone NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: COLUMN magic_link.expires_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.magic_link.expires_at IS '(DC2Type:datetime_immutable)';


--
-- Name: COLUMN magic_link.consumed_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.magic_link.consumed_at IS '(DC2Type:datetime_immutable)';


--
-- Name: COLUMN magic_link.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.magic_link.created_at IS '(DC2Type:datetime_immutable)';


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id uuid NOT NULL,
    token text NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    user_id uuid NOT NULL,
    replaced_by_token character varying(64) DEFAULT NULL::character varying,
    token_digest character varying(64) NOT NULL
);


--
-- Name: COLUMN refresh_token.expires_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.refresh_token.expires_at IS '(DC2Type:datetime_immutable)';


--
-- Name: COLUMN refresh_token.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.refresh_token.created_at IS '(DC2Type:datetime_immutable)';


--
-- Name: stage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stage (
    id uuid NOT NULL,
    "position" integer NOT NULL,
    day_number integer NOT NULL,
    distance double precision NOT NULL,
    elevation double precision NOT NULL,
    elevation_loss double precision NOT NULL,
    start_lat double precision NOT NULL,
    start_lon double precision NOT NULL,
    start_ele double precision NOT NULL,
    end_lat double precision NOT NULL,
    end_lon double precision NOT NULL,
    end_ele double precision NOT NULL,
    geometry jsonb NOT NULL,
    label character varying(255) DEFAULT NULL::character varying,
    is_rest_day boolean NOT NULL,
    weather jsonb,
    alerts jsonb NOT NULL,
    pois jsonb NOT NULL,
    accommodations jsonb NOT NULL,
    selected_accommodation jsonb,
    trip_id uuid NOT NULL,
    ai_analysis jsonb,
    on_cycle_network double precision DEFAULT 0 NOT NULL,
    start_label character varying(255) DEFAULT NULL::character varying,
    end_label character varying(255) DEFAULT NULL::character varying
);


--
-- Name: trip; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip (
    id uuid NOT NULL,
    source_url character varying(2048) DEFAULT NULL::character varying,
    title character varying(255) DEFAULT NULL::character varying,
    start_date date,
    end_date date,
    fatigue_factor double precision NOT NULL,
    elevation_penalty double precision NOT NULL,
    ebike_mode boolean NOT NULL,
    departure_hour integer NOT NULL,
    max_distance_per_day double precision NOT NULL,
    average_speed double precision NOT NULL,
    enabled_accommodation_types text[] NOT NULL,
    source_type character varying(50) DEFAULT NULL::character varying,
    locale character varying(5) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    user_id uuid,
    ai_overview jsonb,
    status character varying(20) DEFAULT 'draft'::character varying NOT NULL,
    out_of_zone boolean DEFAULT false NOT NULL,
    ai_overview_stale boolean DEFAULT false NOT NULL
);


--
-- Name: trip_share; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_share (
    id uuid NOT NULL,
    trip_id uuid NOT NULL,
    token character varying(64) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    short_code character varying(8) DEFAULT ''::character varying NOT NULL
);


--
-- Name: COLUMN trip_share.created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.trip_share.created_at IS '(DC2Type:datetime_immutable)';


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id uuid NOT NULL,
    email character varying(180) NOT NULL,
    roles json NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    locale character varying(5) DEFAULT 'fr'::character varying NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    ai_provider character varying(32) DEFAULT NULL::character varying,
    ai_token text
);


--
-- Name: COLUMN "user".created_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."user".created_at IS '(DC2Type:datetime_immutable)';


--
-- Name: COLUMN "user".deleted_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."user".deleted_at IS '(DC2Type:datetime_immutable)';


--
-- Name: accommodations; Type: TABLE; Schema: tourism; Owner: -
--

CREATE TABLE tourism.accommodations (
    id text NOT NULL,
    name text,
    category text NOT NULL,
    capacity integer,
    price numeric(10,2),
    description text,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    opening_hours text,
    website text,
    phone text,
    image_url text,
    wikipedia_url text,
    wikidata text,
    zone text,
    last_seen_at timestamp with time zone,
    CONSTRAINT accommodations_named CHECK ((NULLIF(btrim(name), ''::text) IS NOT NULL))
);


--
-- Name: cultural_pois; Type: TABLE; Schema: tourism; Owner: -
--

CREATE TABLE tourism.cultural_pois (
    id text NOT NULL,
    name text,
    category text NOT NULL,
    opening_hours text,
    description text,
    wikidata text,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    website text,
    image_url text,
    wikipedia_url text,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: events; Type: TABLE; Schema: tourism; Owner: -
--

CREATE TABLE tourism.events (
    id text NOT NULL,
    name text,
    category text NOT NULL,
    start_date date,
    end_date date,
    url text,
    description text,
    price_min numeric(10,2),
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: food_pois; Type: TABLE; Schema: tourism; Owner: -
--

CREATE TABLE tourism.food_pois (
    id text NOT NULL,
    name text,
    category text NOT NULL,
    opening_hours text,
    description text,
    wikidata text,
    tags jsonb,
    geom public.geometry(Point,4326) NOT NULL,
    website text,
    image_url text,
    wikipedia_url text,
    zone text,
    last_seen_at timestamp with time zone
);


--
-- Name: metadata; Type: TABLE; Schema: tourism; Owner: -
--

CREATE TABLE tourism.metadata (
    refreshed_at timestamp with time zone,
    feature_counts jsonb,
    completeness jsonb,
    rejections jsonb
);


--
-- Name: accommodations accommodations_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.accommodations
    ADD CONSTRAINT accommodations_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: admin_boundaries admin_boundaries_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.admin_boundaries
    ADD CONSTRAINT admin_boundaries_pkey PRIMARY KEY (osm_id);


--
-- Name: bike_shops bike_shops_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.bike_shops
    ADD CONSTRAINT bike_shops_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: charging_stations charging_stations_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.charging_stations
    ADD CONSTRAINT charging_stations_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: cultural_pois cultural_pois_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.cultural_pois
    ADD CONSTRAINT cultural_pois_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: cycle_routes cycle_routes_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.cycle_routes
    ADD CONSTRAINT cycle_routes_pkey PRIMARY KEY (osm_id);


--
-- Name: ferries ferries_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.ferries
    ADD CONSTRAINT ferries_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: fords fords_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.fords
    ADD CONSTRAINT fords_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: health_services health_services_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.health_services
    ADD CONSTRAINT health_services_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: pois pois_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.pois
    ADD CONSTRAINT pois_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: railway_stations railway_stations_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.railway_stations
    ADD CONSTRAINT railway_stations_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: routing_perimeter routing_perimeter_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.routing_perimeter
    ADD CONSTRAINT routing_perimeter_pkey PRIMARY KEY (slug);


--
-- Name: water_points water_points_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.water_points
    ADD CONSTRAINT water_points_pkey PRIMARY KEY (osm_type, osm_id);


--
-- Name: ways ways_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.ways
    ADD CONSTRAINT ways_pkey PRIMARY KEY (osm_id);


--
-- Name: zones zones_pkey; Type: CONSTRAINT; Schema: osm; Owner: -
--

ALTER TABLE ONLY osm.zones
    ADD CONSTRAINT zones_pkey PRIMARY KEY (slug);


--
-- Name: place_enrichment place_enrichment_pkey; Type: CONSTRAINT; Schema: provisioner; Owner: -
--

ALTER TABLE ONLY provisioner.place_enrichment
    ADD CONSTRAINT place_enrichment_pkey PRIMARY KEY (source, source_id);


--
-- Name: wikidata_cache wikidata_cache_pkey; Type: CONSTRAINT; Schema: provisioner; Owner: -
--

ALTER TABLE ONLY provisioner.wikidata_cache
    ADD CONSTRAINT wikidata_cache_pkey PRIMARY KEY (qid);


--
-- Name: access_request access_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_request
    ADD CONSTRAINT access_request_pkey PRIMARY KEY (id);


--
-- Name: email_change_token email_change_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_change_token
    ADD CONSTRAINT email_change_token_pkey PRIMARY KEY (id);


--
-- Name: magic_link magic_link_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.magic_link
    ADD CONSTRAINT magic_link_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: stage stage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stage
    ADD CONSTRAINT stage_pkey PRIMARY KEY (id);


--
-- Name: trip trip_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip
    ADD CONSTRAINT trip_pkey PRIMARY KEY (id);


--
-- Name: trip_share trip_share_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_share
    ADD CONSTRAINT trip_share_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: accommodations accommodations_pkey; Type: CONSTRAINT; Schema: tourism; Owner: -
--

ALTER TABLE ONLY tourism.accommodations
    ADD CONSTRAINT accommodations_pkey PRIMARY KEY (id);


--
-- Name: cultural_pois cultural_pois_pkey; Type: CONSTRAINT; Schema: tourism; Owner: -
--

ALTER TABLE ONLY tourism.cultural_pois
    ADD CONSTRAINT cultural_pois_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: tourism; Owner: -
--

ALTER TABLE ONLY tourism.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: food_pois food_pois_pkey; Type: CONSTRAINT; Schema: tourism; Owner: -
--

ALTER TABLE ONLY tourism.food_pois
    ADD CONSTRAINT food_pois_pkey PRIMARY KEY (id);


--
-- Name: accommodations_category_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX accommodations_category_idx ON osm.accommodations USING btree (category);


--
-- Name: accommodations_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX accommodations_geom_idx ON osm.accommodations USING gist (geom);


--
-- Name: admin_boundaries_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX admin_boundaries_geom_idx ON osm.admin_boundaries USING gist (geom);


--
-- Name: bike_shops_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX bike_shops_geom_idx ON osm.bike_shops USING gist (geom);


--
-- Name: charging_stations_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX charging_stations_geom_idx ON osm.charging_stations USING gist (geom);


--
-- Name: coverage_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX coverage_geom_idx ON osm.coverage USING gist (geom);


--
-- Name: cultural_pois_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX cultural_pois_geom_idx ON osm.cultural_pois USING gist (geom);


--
-- Name: cycle_routes_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX cycle_routes_geom_idx ON osm.cycle_routes USING gist (geom);


--
-- Name: ferries_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX ferries_geom_idx ON osm.ferries USING gist (geom);


--
-- Name: fords_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX fords_geom_idx ON osm.fords USING gist (geom);


--
-- Name: health_services_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX health_services_geom_idx ON osm.health_services USING gist (geom);


--
-- Name: pois_category_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX pois_category_idx ON osm.pois USING btree (category);


--
-- Name: pois_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX pois_geom_idx ON osm.pois USING gist (geom);


--
-- Name: railway_stations_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX railway_stations_geom_idx ON osm.railway_stations USING gist (geom);


--
-- Name: water_points_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX water_points_geom_idx ON osm.water_points USING gist (geom);


--
-- Name: ways_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX ways_geom_idx ON osm.ways USING gist (geom);


--
-- Name: zones_geom_idx; Type: INDEX; Schema: osm; Owner: -
--

CREATE INDEX zones_geom_idx ON osm.zones USING gist (geom);


--
-- Name: place_enrichment_status_version_idx; Type: INDEX; Schema: provisioner; Owner: -
--

CREATE INDEX place_enrichment_status_version_idx ON provisioner.place_enrichment USING btree (status, resolver_version);


--
-- Name: wikidata_cache_fetched_at_idx; Type: INDEX; Schema: provisioner; Owner: -
--

CREATE INDEX wikidata_cache_fetched_at_idx ON provisioner.wikidata_cache USING btree (fetched_at);


--
-- Name: idx_access_request_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_access_request_status ON public.access_request USING btree (status);


--
-- Name: idx_email_change_token_user_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_email_change_token_user_expires ON public.email_change_token USING btree (user_id, expires_at);


--
-- Name: idx_magic_link_user_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_magic_link_user_expires ON public.magic_link USING btree (user_id, expires_at);


--
-- Name: idx_refresh_token_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_token_user ON public.refresh_token USING btree (user_id);


--
-- Name: idx_stage_trip_position; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stage_trip_position ON public.stage USING btree (trip_id, "position");


--
-- Name: idx_trip_share_trip; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trip_share_trip ON public.trip_share USING btree (trip_id);


--
-- Name: idx_trip_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_trip_user ON public.trip USING btree (user_id);


--
-- Name: uniq_access_request_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_access_request_email ON public.access_request USING btree (email);


--
-- Name: uniq_email_change_token_token; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_email_change_token_token ON public.email_change_token USING btree (token);


--
-- Name: uniq_magic_link_token; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_magic_link_token ON public.magic_link USING btree (token);


--
-- Name: uniq_refresh_token_digest; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_refresh_token_digest ON public.refresh_token USING btree (token_digest);


--
-- Name: uniq_trip_share_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_trip_share_active ON public.trip_share USING btree (trip_id) WHERE (deleted_at IS NULL);


--
-- Name: uniq_trip_share_short_code; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_trip_share_short_code ON public.trip_share USING btree (short_code);


--
-- Name: uniq_trip_share_token; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_trip_share_token ON public.trip_share USING btree (token);


--
-- Name: uniq_user_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uniq_user_email ON public."user" USING btree (email);


--
-- Name: accommodations_geom_idx; Type: INDEX; Schema: tourism; Owner: -
--

CREATE INDEX accommodations_geom_idx ON tourism.accommodations USING gist (geom);


--
-- Name: cultural_pois_geom_idx; Type: INDEX; Schema: tourism; Owner: -
--

CREATE INDEX cultural_pois_geom_idx ON tourism.cultural_pois USING gist (geom);


--
-- Name: events_dates_idx; Type: INDEX; Schema: tourism; Owner: -
--

CREATE INDEX events_dates_idx ON tourism.events USING btree (start_date, end_date);


--
-- Name: events_geom_idx; Type: INDEX; Schema: tourism; Owner: -
--

CREATE INDEX events_geom_idx ON tourism.events USING gist (geom);


--
-- Name: food_pois_geom_idx; Type: INDEX; Schema: tourism; Owner: -
--

CREATE INDEX food_pois_geom_idx ON tourism.food_pois USING gist (geom);


--
-- Name: stage fk_c27c9369a5bc2e0e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stage
    ADD CONSTRAINT fk_c27c9369a5bc2e0e FOREIGN KEY (trip_id) REFERENCES public.trip(id) ON DELETE CASCADE;


--
-- Name: email_change_token fk_email_change_token_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_change_token
    ADD CONSTRAINT fk_email_change_token_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: magic_link fk_magic_link_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.magic_link
    ADD CONSTRAINT fk_magic_link_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: refresh_token fk_refresh_token_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: trip_share fk_trip_share_trip; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_share
    ADD CONSTRAINT fk_trip_share_trip FOREIGN KEY (trip_id) REFERENCES public.trip(id) ON DELETE CASCADE;


--
-- Name: trip fk_trip_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip
    ADD CONSTRAINT fk_trip_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


