// A public `GET /s/{code}` payload: two plain stages, no weather or
// accommodations. Rendered by the shared-trip page component tests.
export const MOCK_SHARED_TRIP = {
  "@context": "/contexts/TripShare",
  "@type": "TripDetail",
  id: "share-uuid-abc-999",
  title: "Tour de Bretagne",
  startDate: "2026-07-01T00:00:00+00:00",
  endDate: "2026-07-02T00:00:00+00:00",
  fatigueFactor: 0.85,
  elevationPenalty: 40,
  maxDistancePerDay: 70,
  averageSpeed: 16,
  stages: [
    {
      stageId: "stage-1",
      dayNumber: 1,
      distance: 68.5,
      elevation: 920,
      elevationLoss: 850,
      startPoint: { lat: 47.998, lon: -4.098, ele: 80 },
      endPoint: { lat: 47.742, lon: -3.367, ele: 60 },
      geometry: [],
      label: null,
      weather: null,
      alerts: [],
      resupply: {
        foodAtLunch: [],
        waterMorning: null,
        waterAfternoon: null,
        foodAtArrival: [],
      },
      accommodations: [],
      selectedAccommodation: null,
      isRestDay: false,
    },
    {
      stageId: "stage-2",
      dayNumber: 2,
      distance: 54.2,
      elevation: 640,
      elevationLoss: 710,
      startPoint: { lat: 47.742, lon: -3.367, ele: 60 },
      endPoint: { lat: 47.658, lon: -2.76, ele: 40 },
      geometry: [],
      label: null,
      weather: null,
      alerts: [],
      resupply: {
        foodAtLunch: [],
        waterMorning: null,
        waterAfternoon: null,
        foodAtArrival: [],
      },
      accommodations: [],
      selectedAccommodation: null,
      isRestDay: false,
    },
  ],
};
