/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/trips/{tripId}/stages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add a manual stage at a given position.
     * @description Creates a Stage resource.
     */
    post: operations["api_trips_tripIdstages_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/trips/{tripId}/stages/{index}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete a stage (merge with adjacent).
     * @description Removes the Stage resource.
     */
    delete: operations["api_trips_tripIdstages_index_delete"];
    options?: never;
    head?: never;
    /**
     * Update stage data (start/end points, etc.).
     * @description Updates the Stage resource.
     */
    patch: operations["api_trips_tripIdstages_index_patch"];
    trace?: never;
  };
  "/trips/{tripId}/stages/{index}/move": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Move a stage to a new position.
     * @description Updates the Stage resource.
     */
    patch: operations["api_trips_tripIdstages_indexmove_patch"];
    trace?: never;
  };
  "/trips": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Creates a Trip resource.
     * @description Creates a Trip resource.
     */
    post: operations["api_trips_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/trips/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Updates the Trip resource.
     * @description Updates the Trip resource.
     */
    patch: operations["api_trips_id_patch"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "Accommodation.jsonld": {
      name?: string;
      type?: string;
      lat?: number;
      lon?: number;
      estimatedPriceMin?: number;
      estimatedPriceMax?: number;
      isExactPrice?: boolean;
      url?: string | null;
    };
    "Alert.jsonld": {
      /** @enum {string} */
      type?: "critical" | "warning" | "nudge";
      message?: string;
      lat?: number | null;
      lon?: number | null;
    };
    /** @description Unprocessable entity */
    ConstraintViolation: {
      /** @default 422 */
      status: number;
      violations?: {
        /** @description The property path of the violation */
        propertyPath: string;
        /** @description The message associated with the violation */
        message: string;
        /** @description The code of the violation */
        code?: string;
        /** @description An extra hint to understand the violation */
        hint?: string;
        /** @description The serialized payload of the violation */
        payload?: {
          [key: string]: unknown;
        };
      }[];
      readonly detail?: string;
      readonly type?: string;
      readonly title?: string | null;
      readonly instance?: string | null;
    };
    /** @description Unprocessable entity */
    "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
      /** @default 422 */
      status: number;
      violations?: {
        /** @description The property path of the violation */
        propertyPath: string;
        /** @description The message associated with the violation */
        message: string;
        /** @description The code of the violation */
        code?: string;
        /** @description An extra hint to understand the violation */
        hint?: string;
        /** @description The serialized payload of the violation */
        payload?: {
          [key: string]: unknown;
        };
      }[];
      readonly detail?: string;
      readonly description?: string;
      readonly type?: string;
      readonly title?: string | null;
      readonly instance?: string | null;
    };
    Coordinate: {
      lat?: number;
      lon?: number;
      ele?: number;
    };
    "Coordinate.jsonld": {
      lat?: number;
      lon?: number;
      ele?: number;
    };
    /** @description A representation of common errors. */
    Error: {
      /** @description A short, human-readable summary of the problem. */
      readonly title?: string | null;
      /** @description A human-readable explanation specific to this occurrence of the problem. */
      readonly detail?: string | null;
      /**
       * @default 400
       * @example 404
       */
      status: number | null;
      /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
      readonly instance?: string | null;
      /** @description A URI reference that identifies the problem type */
      readonly type?: string;
    };
    /** @description A representation of common errors. */
    "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
      /** @description A short, human-readable summary of the problem. */
      readonly title?: string | null;
      /** @description A human-readable explanation specific to this occurrence of the problem. */
      readonly detail?: string | null;
      /**
       * @default 400
       * @example 404
       */
      status: number | null;
      /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
      readonly instance?: string | null;
      /** @description A URI reference that identifies the problem type */
      readonly type?: string;
      readonly description?: string | null;
    };
    HydraItemBaseSchema: {
      "@context"?:
        | string
        | ({
            "@vocab": string;
            /** @enum {string} */
            hydra: "http://www.w3.org/ns/hydra/core#";
          } & {
            [key: string]: unknown;
          });
      "@id": string;
      "@type": string;
    };
    "PointOfInterest.jsonld": {
      name?: string;
      category?: string;
      lat?: number;
      lon?: number;
      distanceFromStart?: number | null;
    };
    "Stage.StageRequest": {
      position?: number | null;
      startPoint?: components["schemas"]["Coordinate"] | null;
      endPoint?: components["schemas"]["Coordinate"] | null;
      label?: string | null;
      distance?: number | null;
      toIndex?: number | null;
    };
    "Stage.StageRequest.jsonMergePatch": {
      position?: number | null;
      startPoint?: components["schemas"]["Coordinate"] | null;
      endPoint?: components["schemas"]["Coordinate"] | null;
      label?: string | null;
      distance?: number | null;
      toIndex?: number | null;
    };
    "Stage.StageResponse.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
      weather?: components["schemas"]["WeatherForecast.jsonld"] | null;
      gpxContent?: string | null;
      alerts?: components["schemas"]["Alert.jsonld"][];
      pois?: components["schemas"]["PointOfInterest.jsonld"][];
      accommodations?: components["schemas"]["Accommodation.jsonld"][];
      /**
       * Format: iri-reference
       * @example https://example.com/
       */
      trip?: string;
      dayNumber?: number;
      distance?: number;
      elevation?: number;
      elevationLoss?: number;
      startPoint?: components["schemas"]["Coordinate.jsonld"];
      endPoint?: components["schemas"]["Coordinate.jsonld"];
      geometry?: components["schemas"]["Coordinate.jsonld"][];
      label?: string | null;
    };
    "Stage.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
      weather?: components["schemas"]["WeatherForecast.jsonld"] | null;
      gpxContent?: string | null;
      alerts?: components["schemas"]["Alert.jsonld"][];
      pois?: components["schemas"]["PointOfInterest.jsonld"][];
      accommodations?: components["schemas"]["Accommodation.jsonld"][];
      tripId?: string;
      dayNumber?: number;
      distance?: number;
      elevation?: number;
      startPoint?: components["schemas"]["Coordinate.jsonld"];
      endPoint?: components["schemas"]["Coordinate.jsonld"];
      geometry?: components["schemas"]["Coordinate.jsonld"][];
      label?: string | null;
      elevationLoss?: number;
    };
    "Trip.TripRequest": {
      sourceUrl: string | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      /** @default 0.9 */
      fatigueFactor: number;
      /** @default 50 */
      elevationPenalty: number;
    };
    "Trip.TripRequest.jsonMergePatch": {
      /** Format: uri */
      sourceUrl?: string | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      /** @default 0.9 */
      fatigueFactor: number;
      /** @default 50 */
      elevationPenalty: number;
    };
    "Trip.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
      id?: string;
      /** @description Map of ComputationName->value to status string */
      computationStatus?: {
        [key: string]: string;
      };
    };
    "WeatherForecast.jsonld": {
      icon?: string;
      description?: string;
      tempMin?: number;
      tempMax?: number;
      windSpeed?: number;
      windDirection?: string;
      precipitationProbability?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  api_trips_tripIdstages_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Stage identifier */
        tripId: string;
      };
      cookie?: never;
    };
    /** @description The new Stage resource */
    requestBody: {
      content: {
        "application/ld+json": components["schemas"]["Stage.StageRequest"];
      };
    };
    responses: {
      /** @description Stage resource created */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Stage.StageResponse.jsonld"];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Error.jsonld"];
          "application/problem+json": components["schemas"]["Error"];
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description An error occurred */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
          "application/problem+json": components["schemas"]["ConstraintViolation"];
          "application/json": components["schemas"]["ConstraintViolation"];
        };
      };
    };
  };
  api_trips_tripIdstages_index_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Stage identifier */
        tripId: string;
        /** @description Stage identifier */
        index: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stage resource deleted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Error.jsonld"];
          "application/problem+json": components["schemas"]["Error"];
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  api_trips_tripIdstages_index_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Stage identifier */
        tripId: string;
        /** @description Stage identifier */
        index: string;
      };
      cookie?: never;
    };
    /** @description The updated Stage resource */
    requestBody: {
      content: {
        "application/merge-patch+json": components["schemas"]["Stage.StageRequest.jsonMergePatch"];
      };
    };
    responses: {
      /** @description Stage resource updated */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Stage.StageResponse.jsonld"];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Error.jsonld"];
          "application/problem+json": components["schemas"]["Error"];
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Error.jsonld"];
          "application/problem+json": components["schemas"]["Error"];
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description An error occurred */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
          "application/problem+json": components["schemas"]["ConstraintViolation"];
          "application/json": components["schemas"]["ConstraintViolation"];
        };
      };
    };
  };
  api_trips_tripIdstages_indexmove_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Stage identifier */
        tripId: string;
        /** @description Stage identifier */
        index: string;
      };
      cookie?: never;
    };
    /** @description The updated Stage resource */
    requestBody: {
      content: {
        "application/merge-patch+json": components["schemas"]["Stage.StageRequest.jsonMergePatch"];
      };
    };
    responses: {
      /** @description Stage resource updated */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Stage.StageResponse.jsonld"];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Error.jsonld"];
          "application/problem+json": components["schemas"]["Error"];
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Error.jsonld"];
          "application/problem+json": components["schemas"]["Error"];
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description An error occurred */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
          "application/problem+json": components["schemas"]["ConstraintViolation"];
          "application/json": components["schemas"]["ConstraintViolation"];
        };
      };
    };
  };
  api_trips_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The new Trip resource */
    requestBody: {
      content: {
        "application/ld+json": components["schemas"]["Trip.TripRequest"];
      };
    };
    responses: {
      /** @description Trip resource created */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Trip.jsonld"];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Error.jsonld"];
          "application/problem+json": components["schemas"]["Error"];
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description An error occurred */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
          "application/problem+json": components["schemas"]["ConstraintViolation"];
          "application/json": components["schemas"]["ConstraintViolation"];
        };
      };
    };
  };
  api_trips_id_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Trip identifier */
        id: string;
      };
      cookie?: never;
    };
    /** @description The updated Trip resource */
    requestBody: {
      content: {
        "application/merge-patch+json": components["schemas"]["Trip.TripRequest.jsonMergePatch"];
      };
    };
    responses: {
      /** @description Trip resource updated */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Trip.jsonld"];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Error.jsonld"];
          "application/problem+json": components["schemas"]["Error"];
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["Error.jsonld"];
          "application/problem+json": components["schemas"]["Error"];
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description An error occurred */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
          "application/problem+json": components["schemas"]["ConstraintViolation"];
          "application/json": components["schemas"]["ConstraintViolation"];
        };
      };
    };
  };
}
