"use client";

import { useState, useCallback } from "react";
import { Sparkles, ChevronDown } from "lucide-react";
import { useTranslations } from "next-intl";

/** Threshold above which the summary is clamped behind a "show more" toggle. */
const LONG_SUMMARY_CHAR_THRESHOLD = 220;

interface StageAiSummaryProps {
  summary: string;
  /** Optional override for the long-summary threshold (mostly useful for tests). */
  longThreshold?: number;
}

/**
 * Top-of-panel narrative summary generated by an AI for the current stage.
 *
 * Visual design (sprint 25 / 26):
 * - Soft gradient card with subtle ring, sparkle icon and Fraunces italic
 *   typography to differentiate AI-authored content from factual data blocks.
 * - Long summaries (> {@link LONG_SUMMARY_CHAR_THRESHOLD} chars) are clamped
 *   behind a chevron toggle that follows the design-system rotation pattern.
 *   Short summaries render in full with no toggle.
 */
export function StageAiSummary({
  summary,
  longThreshold = LONG_SUMMARY_CHAR_THRESHOLD,
}: StageAiSummaryProps) {
  const t = useTranslations("stageAiSummary");
  const isLong = summary.length > longThreshold;
  // Re-sync expanded state when the summary length crosses the threshold
  // (e.g. SSE delivers a long summary after mount with an initial empty/short
  // string). Without this, the toggle would render "Show less" even though
  // the text is fully visible. Using the official React "adjusting state on
  // prop change" pattern (https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes)
  // avoids cascading effect renders.
  const [expanded, setExpanded] = useState(!isLong);
  const [prevIsLong, setPrevIsLong] = useState(isLong);
  if (prevIsLong !== isLong) {
    setPrevIsLong(isLong);
    setExpanded(!isLong);
  }
  const toggle = useCallback(() => setExpanded((prev) => !prev), []);

  return (
    <section
      data-testid="stage-ai-summary"
      aria-label={t("ariaLabel")}
      className="relative overflow-hidden rounded-xl border border-primary/20 bg-gradient-to-br from-primary/5 via-background to-background p-4 shadow-sm"
    >
      <div className="flex items-start gap-3">
        <div
          aria-hidden="true"
          className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary"
        >
          <Sparkles className="h-4 w-4" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-[11px] font-medium uppercase tracking-wider text-primary/80">
            {t("label")}
          </p>
          <p
            className={`mt-1 font-serif italic text-sm md:text-base leading-relaxed text-foreground ${
              isLong && !expanded ? "line-clamp-3" : ""
            }`}
            data-testid="stage-ai-summary-text"
            data-expanded={expanded}
          >
            {summary}
          </p>
          {isLong && (
            <button
              type="button"
              onClick={toggle}
              aria-expanded={expanded}
              data-testid="stage-ai-summary-toggle"
              className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-primary hover:text-primary/80 transition-colors cursor-pointer"
            >
              <span>{expanded ? t("showLess") : t("showMore")}</span>
              <ChevronDown
                className={`h-3.5 w-3.5 transition-transform duration-200 ${
                  expanded ? "rotate-180" : "rotate-0"
                }`}
                aria-hidden="true"
              />
            </button>
          )}
        </div>
      </div>
    </section>
  );
}
