name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_ENV: test
  NODE_ENV: test

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Fix repository ownership
        run: git config --global --add safe.directory $(pwd)
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: cd api/
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts --no-progress
      - name: Run PHPUnit
        run: vendor/bin/phpunit

  openapi-lint:
    name: OpenAPI Lint
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Fix repository ownership
        run: git config --global --add safe.directory $(pwd)
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: cd api/
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts --no-progress
      - name: Run Redocly
        run: bin/console api:openapi:export --yaml | redocly lint /dev/stdin

  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Fix repository ownership
        run: git config --global --add safe.directory $(pwd)
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: cd api/
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts --no-progress
      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --ansi

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Fix repository ownership
        run: git config --global --add safe.directory $(pwd)
      - name: Run Markdownlint
        run: markdownlint "**/*.md"

  symfony-security-check:
    name: Security Check
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Fix repository ownership
        run: git config --global --add safe.directory $(pwd)
      - run: cd api/
      - name: Run Symfony Security Check
        run: symfony check:security

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Fix repository ownership
        run: git config --global --add safe.directory $(pwd)
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: cd api/
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts --no-progress
      - name: WarmUp Cache
        env:
          APP_ENV: dev # required for parameters.symfony.containerXmlPath
        run: bin/console cache:warmup --no-optional-warmers
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.dist.neon

  rector:
    name: Rector
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Fix repository ownership
        run: git config --global --add safe.directory $(pwd)
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: cd api/
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts --no-progress
      - name: Run Rector
        run: vendor/bin/rector process --dry-run

  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
      - name: Get NPM cache directory
        id: npm-cache
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - run: cd pwa/
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    container:
      image: node:25-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get NPM cache directory
        id: npm-cache
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - run: cd pwa/
      - name: Install dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run lint

  typescript-check:
    name: TypeScript Check
    runs-on: ubuntu-latest
    container:
      image: node:25-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get NPM cache directory
        id: npm-cache
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - run: cd pwa/
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript Check
        run: npm run test:ts
